name: Release branch

on:
  push:
    branches:
      - main
      - dev


concurrency: ${{ github.workflow }}-${{ github.ref }}

jobs:
  update-release:
    if: github.ref_name == 'dev'
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    name: Update (Or create) release branch
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup environment
        uses: ./.github/actions/pnpm-setup

      - name: Update release PR
        id: changesets
        uses: loreddev/changeset-action@main
        with:
          branch: main
          commit: 'chore: 🔗🦋 version packages'
          title: '🦋 Release branch'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  update-dev:
    if: github.ref_name == 'main'
    runs-on: ubuntu-latest
    name: Update dev branch
    env:
      HUSKY: 0
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Release to dev
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: "changeset-release/main"
          target_branch: "dev"
          github_token: ${{ secrets.GITHUB_TOKEN }}

